// Claude Code export package (Task 10). Produces a developer-ready markdown
// bundle from a platform-neutral Automation Blueprint + recommended MCP
// connectors — NOT an n8n workflow. Everything here is deterministic templating
// so the package faithfully reflects the Blueprint (business rules, retry, and
// tests appear verbatim) and contains no n8n node names.

const OP_PHRASE = {
  equals: 'is', not_equals: 'is not', in: 'is one of', not_in: 'is not one of',
  greater_than: '>', greater_or_equal: '>=', less_than: '<', less_or_equal: '<=',
  contains: 'contains', exists: 'exists',
};

const nn = (v) => (v === null || v === undefined || v === '' ? null : v);
const list = (arr) => (Array.isArray(arr) ? arr : []);

function envName(name, suffix = 'API_KEY') {
  const base = String(name || 'service').toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_+|_+$/g, '');
  return `${base}_${suffix}`;
}

function renderCondition(c) {
  if (!c) return '';
  const op = OP_PHRASE[c.operator] || c.operator;
  return `\`${c.field}\` ${op} ${list(c.value).map((v) => `\`${v}\``).join(', ')}`;
}

// Pull likely env-var names out of an MCP server's config_json.
function extractMcpEnvKeys(configJson) {
  const keys = new Set();
  if (!configJson) return keys;
  try {
    const cfg = typeof configJson === 'string' ? JSON.parse(configJson) : configJson;
    const servers = cfg?.mcpServers || cfg || {};
    for (const server of Object.values(servers)) {
      if (server?.env && typeof server.env === 'object') {
        Object.keys(server.env).forEach((k) => keys.add(k));
      }
      for (const a of list(server?.args)) {
        if (typeof a === 'string' && /^[A-Z][A-Z0-9_]{2,}$/.test(a)) keys.add(a);
      }
    }
  } catch { /* not valid JSON — fall through to regex */ }
  // Regex fallback for secret-looking tokens anywhere in the string.
  const raw = typeof configJson === 'string' ? configJson : JSON.stringify(configJson);
  for (const m of raw.match(/[A-Z][A-Z0-9_]*(?:TOKEN|KEY|SECRET|PASSWORD|_ID)\b/g) || []) keys.add(m);
  return keys;
}

// Decide, per system, the best-fit MCP (or none → API/custom integration).
function chooseMcpForSystem(systemName, mcp) {
  const recs = (mcp.perSystem && mcp.perSystem[systemName]) || [];
  if (recs.length === 0) return { rec: null, alts: [] };
  const lname = String(systemName).toLowerCase();
  const mentions = (r) => `${r.name} ${r.description} ${r.tags}`.toLowerCase().includes(lname);
  const best = recs[0];
  const fits = best && (best.score >= 0.5 || mentions(best));
  return fits ? { rec: best, alts: recs.slice(1, 3) } : { rec: null, alts: recs.slice(0, 2) };
}

// ---------------------------------------------------------------------------
// Individual files
// ---------------------------------------------------------------------------

function readme(bp) {
  return `# ${bp.name || 'Automation'} — Claude Code Implementation Package

This is a **developer-ready package** for building the automation described in
the Vyrade Automation Blueprint using **Claude Code**. It is intentionally NOT a
workflow JSON — Claude Code is not a workflow engine. Instead it gives Claude
(and you) the architecture, requirements, business rules, recommended MCP
connectors, environment variables, acceptance tests, and deployment notes needed
to implement the automation in code.

## How to use
1. Open this folder in Claude Code (web, VS Code, or a GitHub repo).
2. Read \`claude-prompt.md\` and paste it as your instruction to Claude Code
   (or click **Copy Claude Prompt** in Vyrade).
3. Install the recommended MCP servers from \`recommended-mcps.md\` and fill in
   \`.env.example\` (copy to \`.env\`).
4. Implement, then validate against \`acceptance-tests.md\`.

## Contents
- \`README.md\` — this file
- \`architecture.md\` — high-level design & data flow
- \`requirements.md\` — what must be built (platform-neutral)
- \`business-rules.md\` — rules, exceptions, retry & notification policy
- \`claude-prompt.md\` — ready-to-paste instruction for Claude Code
- \`recommended-mcps.md\` — MCP connectors to use and why
- \`.env.example\` — placeholder environment variables
- \`acceptance-tests.md\` — tests derived from the Blueprint
- \`deployment-notes.md\` — how to ship it

_Generated by Vyrade from Automation Blueprint \`${bp.name || ''}\`._
`;
}

function architecture(bp) {
  const steps = list(bp.process_steps).slice().sort((a, b) => a.sequence - b.sequence);
  const trigger = bp.trigger || {};
  const flow = [
    `**Trigger** — ${nn(trigger.event) || nn(trigger.trigger_type) || 'unspecified'}${nn(trigger.source_system) ? ` (from ${trigger.source_system})` : ''}`,
    ...steps.map((s, i) => `**Step ${i + 1}** — ${s.action} _(${s.action_type})_`),
  ];
  return `# Architecture

## Goal
${nn(bp.business_intent?.business_goal) || '—'}

## Data flow
${flow.map((f) => `1. ${f}`).join('\n')}

## Systems involved
${list(bp.systems).map((s) => `- **${s.name}** — ${s.role}${s.required ? ' (required)' : ''}`).join('\n') || '- None specified'}

## Human approval
${bp.human_approval?.required === true
    ? `Required at: ${list(bp.human_approval.approval_points).join(', ') || 'unspecified point(s)'}.`
    : bp.human_approval?.required === false ? 'Not required — fully automated.' : 'Not specified.'}

## Notifications
${list(bp.notification_rules).map((n) => `- On **${n.condition}** (${n.event}) notify **${n.audience}** via **${n.channel_system}**`).join('\n') || '- None specified'}
`;
}

function requirements(bp) {
  const di = list(bp.data_inputs);
  const c = bp.constraints || {};
  const ic = c.implementation_constraints || {};
  const vol = bp.volume || {};
  return `# Requirements

## Business intent
- **Goal:** ${nn(bp.business_intent?.business_goal) || '—'}
- **Desired outcome:** ${nn(bp.business_intent?.desired_outcome) || '—'}

## Trigger
- **Type:** ${nn(bp.trigger?.trigger_type) || '—'}
- **Event:** ${nn(bp.trigger?.event) || '—'}
- **Source system:** ${nn(bp.trigger?.source_system) || '—'}
- **Schedule:** ${nn(bp.trigger?.schedule) || '—'}

## Systems
${list(bp.systems).map((s) => `- **${s.name}** (${s.role})${s.required ? ' — required' : ''}`).join('\n') || '- None specified'}

## Data inputs
${di.length ? di.map((d) => `- \`${d.field}\`${d.required ? ' (required)' : ''}${nn(d.source) ? ` — from ${d.source}` : ''}`).join('\n') : '- None specified'}

## Process steps
${list(bp.process_steps).slice().sort((a, b) => a.sequence - b.sequence).map((s) => `${s.sequence}. ${s.action} _(${s.action_type})_`).join('\n') || '- None specified'}

## Volume
- **Estimated executions:** ${nn(vol.estimated_executions) ?? '—'}${nn(vol.period) ? ` per ${vol.period}` : ''} (confidence: ${vol.confidence || 'unknown'})

## Constraints
- **Budget:** ${nn(c.budget) || '—'}
- **Technical skill:** ${nn(c.technical_skill) || '—'}
- **Self-hosting required:** ${c.self_hosting_required == null ? '—' : c.self_hosting_required ? 'yes' : 'no'}
- **Security:** ${list(c.security_requirements).join(', ') || '—'}
- **Compliance:** ${list(c.compliance_requirements).join(', ') || '—'}
- **Latency:** ${nn(c.latency_requirement) || '—'}
- **Required platforms:** ${list(ic.required_platforms).join(', ') || '—'}
- **Prohibited platforms:** ${list(ic.prohibited_platforms).join(', ') || '—'}
- **Existing platforms:** ${list(ic.existing_platforms).join(', ') || '—'}

## Open questions
${list(bp.unknown_requirements).map((u) => `- ${u.reason}${u.blocks_generation ? ' _(blocks implementation)_' : ''}`).join('\n') || '- None'}
`;
}

function businessRules(bp) {
  const rules = list(bp.business_rules);
  const exc = list(bp.exception_rules);
  const retry = list(bp.retry_requirements);
  const notif = list(bp.notification_rules);
  return `# Business Rules

## Decision rules
${rules.length
    ? rules.map((r) => `- **${r.description || r.rule_id}:** when ${renderCondition(r.condition)} → **${r.result.action}** = \`${r.result.value}\``).join('\n')
    : '- None specified'}

## Exception handling
${exc.length
    ? exc.map((e) => `- **${e.scenario}:** ${e.behavior}${list(e.data_changes).length ? ` (set ${e.data_changes.map((d) => `\`${d.field}\`=\`${d.value}\``).join(', ')})` : ''}`).join('\n')
    : '- None specified'}

## Retry policy
${retry.length
    ? retry.map((r) => `- **${r.system}:** retry up to **${r.max_retries}** time(s); on final failure → ${nn(r.after_final_failure) || 'stop'}`).join('\n')
    : '- None specified'}

## Notifications
${notif.length
    ? notif.map((n) => `- On **${n.condition}** (${n.event}): notify **${n.audience}** via **${n.channel_system}**`).join('\n')
    : '- None specified'}

## Human approval
${bp.human_approval?.required === true
    ? `Required before: ${list(bp.human_approval.approval_points).join(', ') || 'the affected step(s)'}.`
    : bp.human_approval?.required === false ? 'Not required.' : 'Not specified.'}
`;
}

function recommendedMcps(bp, mcp) {
  const systems = list(bp.systems);
  const blocks = systems.map((s) => {
    const { rec, alts } = chooseMcpForSystem(s.name, mcp);
    if (!rec) {
      return `### ${s.name} (${s.role})
No well-matched MCP connector was found. **Recommendation:** integrate ${s.name}
directly via its **REST API / official SDK** (custom integration).${alts.length ? `
_Closest catalog matches (verify fit): ${alts.map((a) => a.name).join(', ')}._` : ''}
`;
    }
    const envKeys = [...extractMcpEnvKeys(rec.config)];
    return `### ${s.name} (${s.role}) → ${rec.name}
${rec.description || ''}

- **Why:** best-matched MCP connector for **${s.name}** in the Vyrade MCP catalog.
${rec.repository ? `- **Repository:** ${rec.repository}\n` : ''}${rec.url ? `- **Details:** ${rec.url}\n` : ''}${rec.tags ? `- **Category:** ${rec.tags}\n` : ''}${envKeys.length ? `- **Required env:** ${envKeys.map((k) => `\`${k}\``).join(', ')}\n` : ''}${rec.config ? `
\`\`\`json
${(() => { try { return JSON.stringify(JSON.parse(rec.config), null, 2); } catch { return rec.config; } })()}
\`\`\`
` : ''}
> ⚠️ Caveat: verify the server is actively maintained, review the scopes/permissions
> it requests, and confirm it supports the operations this automation needs before
> relying on it in production.${alts.length ? ` Alternatives: ${alts.map((a) => a.name).join(', ')}.` : ''}
`;
  });

  return `# Recommended MCP Connectors

Claude Code can use MCP servers/connectors to reach external systems. Below is a
recommendation per system in the Blueprint. Where no suitable MCP exists, a
direct API / custom integration is recommended instead.

${blocks.join('\n') || '_No systems specified in the Blueprint._'}
`;
}

function claudePrompt(bp, mcp) {
  const goal = nn(bp.business_intent?.business_goal) || 'the described automation';
  const mcpLines = list(bp.systems).map((s) => {
    const { rec } = chooseMcpForSystem(s.name, mcp);
    return rec
      ? `- Use **${rec.name}** (MCP) for **${s.name}** (${s.role}).`
      : `- Integrate **${s.name}** (${s.role}) via its REST API (no MCP available).`;
  });
  const rules = list(bp.business_rules).map((r) => `- When ${renderCondition(r.condition)} → ${r.result.action} = \`${r.result.value}\`.`);
  const retry = list(bp.retry_requirements).map((r) => `- ${r.system}: retry ${r.max_retries}×, then ${nn(r.after_final_failure) || 'stop'}.`);
  const notif = list(bp.notification_rules).map((n) => `- Notify ${n.audience} via ${n.channel_system} on ${n.condition}.`);

  return `# Claude Code Prompt

Copy everything below into Claude Code as your instruction.

---

Build this automation based on the attached Automation Blueprint. The objective
is: **${goal}**.

**Connectors to use**
${mcpLines.join('\n') || '- (No systems specified.)'}

**Trigger**
- ${nn(bp.trigger?.event) || nn(bp.trigger?.trigger_type) || 'as specified in requirements.md'}${nn(bp.trigger?.source_system) ? ` from ${bp.trigger.source_system}` : ''}.

**Business rules (implement exactly)**
${rules.join('\n') || '- See business-rules.md.'}

**Retry policy (implement exactly)**
${retry.join('\n') || '- See business-rules.md.'}

**Notifications**
${notif.join('\n') || '- See business-rules.md.'}

**Human approval**
- ${bp.human_approval?.required === true ? `Require human approval before: ${list(bp.human_approval.approval_points).join(', ') || 'the affected step(s)'}.` : bp.human_approval?.required === false ? 'No human approval required.' : 'See requirements.md.'}

Follow \`requirements.md\` and \`business-rules.md\` precisely, read secrets from
environment variables (see \`.env.example\`), and implement automated tests that
satisfy every case in \`acceptance-tests.md\`. Do not hardcode credentials.
`;
}

function envExample(bp, mcp) {
  const lines = [
    '# Environment variables for this automation.',
    '# Copy to .env and fill in real values. Never commit .env.',
    '',
  ];
  // Per-system API keys.
  const seen = new Set();
  for (const s of list(bp.systems)) {
    const key = envName(s.name);
    if (seen.has(key)) continue;
    seen.add(key);
    lines.push(`# ${s.name} (${s.role})`);
    lines.push(`${key}=`);
  }
  // Env keys required by the recommended MCP servers.
  const mcpKeys = new Set();
  for (const s of list(bp.systems)) {
    const { rec } = chooseMcpForSystem(s.name, mcp);
    if (rec) extractMcpEnvKeys(rec.config).forEach((k) => mcpKeys.add(k));
  }
  const extra = [...mcpKeys].filter((k) => !seen.has(k));
  if (extra.length) {
    lines.push('', '# Required by recommended MCP servers');
    for (const k of extra) lines.push(`${k}=`);
  }
  if (seen.size === 0 && extra.length === 0) {
    lines.push('# No external credentials detected in the Blueprint.');
  }
  return lines.join('\n') + '\n';
}

function acceptanceTests(bp) {
  const t = [];
  const trig = bp.trigger || {};
  t.push(`- [ ] **Trigger:** when ${nn(trig.event) || nn(trig.trigger_type) || 'the trigger'} occurs${nn(trig.source_system) ? ` in ${trig.source_system}` : ''}, the automation starts.`);

  list(bp.business_rules).forEach((r) => {
    t.push(`- [ ] **Rule (${r.description || r.rule_id}):** given ${renderCondition(r.condition)}, the result is **${r.result.action}** = \`${r.result.value}\`.`);
  });
  list(bp.exception_rules).forEach((e) => {
    t.push(`- [ ] **Exception:** given "${e.scenario}", the system ${e.behavior}.`);
  });
  list(bp.retry_requirements).forEach((r) => {
    t.push(`- [ ] **Retry:** when **${r.system}** fails, it is retried up to **${r.max_retries}** time(s); after the final failure it ${nn(r.after_final_failure) || 'stops'}.`);
  });
  list(bp.notification_rules).forEach((n) => {
    t.push(`- [ ] **Notification:** on **${n.condition}** (${n.event}), **${n.audience}** is notified via **${n.channel_system}**.`);
  });
  if (bp.human_approval?.required === true) {
    t.push(`- [ ] **Approval:** the process pauses for human approval before ${list(bp.human_approval.approval_points).join(', ') || 'the affected step(s)'} and only continues once approved.`);
  }
  // Happy path end-to-end.
  t.push(`- [ ] **End-to-end:** a representative input flows through all steps and produces the desired outcome: ${nn(bp.business_intent?.desired_outcome) || 'as specified'}.`);

  return `# Acceptance Tests

These are derived directly from the Blueprint's rules, exceptions, retry policy,
and notifications. Implement automated tests that cover every item.

${t.join('\n')}
`;
}

function deploymentNotes(bp) {
  const c = bp.constraints || {};
  const notes = [];
  notes.push('1. Copy `.env.example` to `.env` and fill in real credentials.');
  notes.push('2. Install the MCP servers listed in `recommended-mcps.md` and register them with Claude Code.');
  notes.push('3. Run the automated tests in `acceptance-tests.md` before shipping.');
  if (c.self_hosting_required) notes.push('4. Self-hosting is required — deploy on your own infrastructure rather than a shared SaaS runtime.');
  if (list(c.security_requirements).length) notes.push(`5. Security requirements to satisfy: ${c.security_requirements.join(', ')}.`);
  if (list(c.compliance_requirements).length) notes.push(`6. Compliance to satisfy: ${c.compliance_requirements.join(', ')}.`);
  if (nn(c.latency_requirement)) notes.push(`7. Latency target: ${c.latency_requirement}.`);
  notes.push('- Store all secrets in environment variables / a secrets manager — never in code.');
  notes.push('- Add logging and monitoring around external calls, and alerting on the retry "final failure" paths.');
  return `# Deployment Notes

${notes.map((n) => (n.startsWith('-') ? n : n)).join('\n')}
`;
}

/**
 * Build the full Claude Code package.
 * @param {object} args
 * @param {object} args.bp   The Blueprint content.
 * @param {object} args.mcp  Result of retrieveMcpForSystems (perSystem, all…).
 * @returns {{ files: Record<string,string>, prompt: string }}
 */
export function buildClaudePackage({ bp, mcp = { perSystem: {}, all: [] } }) {
  const prompt = claudePrompt(bp, mcp);
  const files = {
    'README.md': readme(bp),
    'architecture.md': architecture(bp),
    'requirements.md': requirements(bp),
    'business-rules.md': businessRules(bp),
    'claude-prompt.md': prompt,
    'recommended-mcps.md': recommendedMcps(bp, mcp),
    '.env.example': envExample(bp, mcp),
    'acceptance-tests.md': acceptanceTests(bp),
    'deployment-notes.md': deploymentNotes(bp),
  };
  return { files, prompt };
}
